import { AppShell, ScreenContainer, CosmicBackground, StarField, NebulaGlow, MysticCard, AppHeader, BrandLogo, IconButton, SectionTitle, GlowDivider, MysticButton, InfoBanner, StatusBadge, ProgressBar, Tabs, BottomNavigation, BottomNavItem, CenterMagicButton, GreetingCard, UserAvatar, BalanceCard, SilarumCoin, FortuneWheelCard, FortuneWheel, WheelSegment, WheelPointer, WheelCenter, QuickAccessGrid, ShortcutCard, ShortcutBadge, UploadCard, GoalSelector, GoalChip, EnergyHandsScene, PalmGraphic, EnergyLink, HeartCore, MagicParticleField, PriceLine, ServiceCard, ServiceArtwork, DataStatusCard, MediaThumbnail, ActionGroup, CompatibilityHero, PersonPortrait, PersonMeta, MetricsList, MetricRow, ForecastGrid, ForecastCard, FinalScoreCard, ShareActions } from "./components/index.js";
import { HomeScreen, PalmLinkScreen, RitualScreen, CompatibilityResultScreen } from "./screens/index.js";

const gallery = document.querySelector("#gallery");
function add(name, node, wide=false) {
  const item=document.createElement("section");
  item.className="n-gallery-item";
  if (wide) item.style.gridColumn="1 / -1";
  const title=document.createElement("h2");
  title.textContent=name;
  const stage=document.createElement("div");
  stage.className="n-gallery-stage";
  stage.append(node);
  item.append(title,stage);
  gallery.append(item);
}

add("01 AppShell", AppShell({children:[ScreenContainer({children:[SectionTitle({text:"Каркас приложения"})]})]}));
add("02 ScreenContainer", ScreenContainer({children:[MysticCard({children:["Контейнер экрана"]})]}));
add("03 CosmicBackground", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:150px;overflow:hidden;border-radius:14px";n.append(CosmicBackground());return n;})());
add("04 StarField", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:150px;background:#070913;overflow:hidden";n.append(StarField());return n;})());
add("05 NebulaGlow", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:150px;background:#070913;overflow:hidden";n.append(NebulaGlow());return n;})());
add("06 MysticCard", MysticCard({children:["Универсальная мистическая карточка"],className:"n-info-banner"}));
add("07 AppHeader", AppHeader({title:"Путь двух судеб",subtitle:"Найди свою связь через ладони"}));
add("08 BrandLogo", BrandLogo());
add("09 IconButton", IconButton({icon:"bell",label:"Уведомления"}));
add("10 SectionTitle", SectionTitle({text:"Быстрый доступ"}));
add("11 GlowDivider", GlowDivider());
add("12 MysticButton", (()=>{const n=document.createElement("div");n.style.display="grid";n.style.gap="8px";n.append(MysticButton({text:"Основное действие",variant:"primary"}),MysticButton({text:"Золотое действие",variant:"gold"}),MysticButton({text:"Контурная кнопка",variant:"outline"}));return n;})());
add("13 InfoBanner", InfoBanner({text:"Партнёр получит ссылку и сможет добавить свои данные."}));
add("14 StatusBadge", StatusBadge({text:"Готово"}));
add("15 ProgressBar", ProgressBar({value:88}));
add("16 Tabs", Tabs({active:0}));
add("17 BottomNavigation", BottomNavigation({active:"home"}));
add("18 BottomNavItem", BottomNavItem({icon:"home",label:"Главная",active:true}));
add("19 CenterMagicButton", CenterMagicButton());
add("20 GreetingCard", GreetingCard());
add("21 UserAvatar", UserAvatar());
add("22 BalanceCard", BalanceCard());
add("23 SilarumCoin", SilarumCoin());
add("24 FortuneWheelCard", FortuneWheelCard(), true);
add("25 FortuneWheel", FortuneWheel());
add("26 WheelSegment", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:110px";n.append(WheelSegment({value:250,angle:0}));return n;})());
add("27 WheelPointer", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:60px";n.append(WheelPointer());return n;})());
add("28 WheelCenter", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:80px";n.append(WheelCenter());return n;})());
add("29 QuickAccessGrid", QuickAccessGrid());
add("30 ShortcutCard", ShortcutCard({icon:"tarot",title:"Таро расклад"}));
add("31 ShortcutBadge", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:50px";n.append(ShortcutBadge({text:"+1"}));return n;})());
add("32 UploadCard", UploadCard());
add("33 GoalSelector", GoalSelector({value:"love"}));
add("34 GoalChip", GoalChip({icon:"heart",label:"Любовь",active:true}));
add("35 EnergyHandsScene", EnergyHandsScene(), true);
add("36 PalmGraphic", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:230px";n.append(PalmGraphic({side:"left"}));return n;})());
add("37 EnergyLink", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:90px";n.append(EnergyLink());return n;})());
add("38 HeartCore", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:90px";n.append(HeartCore());return n;})());
add("39 MagicParticleField", (()=>{const n=document.createElement("div");n.style.cssText="position:relative;height:130px;background:#070913";n.append(MagicParticleField());return n;})());
add("40 PriceLine", PriceLine());
add("41 ServiceCard", ServiceCard());
add("42 ServiceArtwork", ServiceArtwork());
add("43 DataStatusCard", DataStatusCard());
add("44 MediaThumbnail", MediaThumbnail());
add("45 ActionGroup", ActionGroup());
add("46 CompatibilityHero", CompatibilityHero());
add("47 PersonPortrait", PersonPortrait({gender:"female"}));
add("48 PersonMeta", PersonMeta({name:"Алиса",birthDate:"18.07.1994"}));
add("49 MetricsList", MetricsList(), true);
add("50 MetricRow", MetricRow({icon:"hand",title:"Резонанс ладоней",description:"Схожесть линий и энергетики",score:92}));
add("51 ForecastGrid", ForecastGrid());
add("52 ForecastCard", ForecastCard({icon:"heart",label:"Любовь",score:94}));
add("53 FinalScoreCard", FinalScoreCard());
add("54 ShareActions", ShareActions());

const screens=document.querySelector("#screens");
[["Главная",HomeScreen()],["Путь двух судеб",PalmLinkScreen()],["Совместный ритуал",RitualScreen()],["Результат",CompatibilityResultScreen()]].forEach(([name,node])=>{
 const item=document.createElement("section"); item.className="n-gallery-item"; 
 const h=document.createElement("h2"); h.textContent=name;
 const frame=document.createElement("div"); frame.className="n-screen-preview"; frame.append(...node.childNodes);
 item.append(h,frame); screens.append(item);
});
