alter table public.nastardamus_admins
  add column if not exists display_name text,
  add column if not exists username text,
  add column if not exists permissions jsonb not null default '{}'::jsonb,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_by bigint,
  add column if not exists last_seen_at timestamptz;

create index if not exists nastardamus_admins_active_idx
  on public.nastardamus_admins (is_active, role);

create table if not exists public.nastardamus_support_settings (
  key text primary key,
  enabled boolean not null default true,
  support_username text,
  support_chat_id bigint,
  welcome_message text not null default 'Здравствуйте! Опишите вопрос, и команда поддержки ответит вам.',
  offline_message text not null default 'Сейчас операторы не в сети. Мы ответим в рабочее время.',
  working_hours jsonb not null default '{"timezone":"Europe/Berlin","days":[1,2,3,4,5],"from":"09:00","to":"18:00"}'::jsonb,
  response_sla_minutes integer not null default 240 check (response_sla_minutes between 5 and 10080),
  allow_attachments boolean not null default true,
  auto_assign boolean not null default true,
  updated_by bigint,
  updated_at timestamptz not null default now()
);

insert into public.nastardamus_support_settings (key)
values ('global')
on conflict (key) do nothing;

create table if not exists public.nastardamus_support_tickets (
  id bigint generated by default as identity primary key,
  user_telegram_id bigint not null,
  subject text,
  status text not null default 'open' check (status in ('open','pending','resolved','closed')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_admin_id bigint references public.nastardamus_admins(telegram_id) on delete set null,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists nastardamus_support_tickets_queue_idx
  on public.nastardamus_support_tickets (status, priority, last_message_at desc);

alter table public.nastardamus_admins enable row level security;
alter table public.nastardamus_support_settings enable row level security;
alter table public.nastardamus_support_tickets enable row level security;
