create table if not exists public.nastardamus_settings (
  key text primary key,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.nastardamus_admins (
  telegram_id bigint primary key,
  role text not null default 'admin' check (role in ('owner','admin','moderator')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nastardamus_admin_audit (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.nastardamus_settings enable row level security;
alter table public.nastardamus_admins enable row level security;
alter table public.nastardamus_admin_audit enable row level security;

revoke all on public.nastardamus_settings from anon, authenticated;
revoke all on public.nastardamus_admins from anon, authenticated;
revoke all on public.nastardamus_admin_audit from anon, authenticated;

insert into public.nastardamus_settings (key, settings)
values (
  'global',
  '{"withdrawalFee":25,"minimumWithdrawal":25,"withdrawalsEnabled":false,"wheelEnabled":true,"wheelPrizeShare":50,"wheelMaxPrize":1000,"referralsEnabled":true,"firstReferralRate":50,"repeatReferralRate":13,"palmLinkEnabled":false,"jointReadingsEnabled":true,"partnerPaymentEnabled":true,"manualPhotoReview":true,"adultOnly":true}'::jsonb
)
on conflict (key) do nothing;
